spring.application.name=edu

server.port=${SERVER_PORT}


// Base de datos MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL}

# JWT settings
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}